### ISSUE TITLE
`AyaLsp#isWatched` works incorrectly

### ISSUE THREAD

**Issue by HoshinoTented** [aya-prover/intellij-aya#31]
https://github.com/aya-prover/intellij-aya/blob/09d32944fa36598507f4b09e1d28d193d2d4fe47/src/main/java/org/aya/intellij/actions/lsp/AyaLsp.java#L198

```plain
+ Library Root
  + src
     - watched.aya
  - aya.json
  - not-watched.aya
```

File `not-watched.aya` is also `isWatched` even though the lsp doesn't load it.

**Comment by imkiva** [comment]
😱

**Comment by HoshinoTented** [comment]
Cause `isInLibrary` checks whether a file is `under` a library.

**Comment by ice1000** [comment]
I fixed it by only adding the `modulePath` to the cache.
